### ISSUE TITLE
Error in tindetheus.py:show_images line:153

### ISSUE THREAD

**Issue by pbamotra** [cjekel/tindetheus#1] opened 2018-03-14 22:28 UTC
OS: Mac OS X
Python dist: Anaconda 2

Traceback (most recent call last):
  File "/anaconda/bin/tindetheus", line 11, in <module>
    sys.exit(command_line_run())
  File "/anaconda/lib/python2.7/site-packages/tindetheus/tindetheus.py", line 567, in command_line_run
    main(parse_arguments(sys.argv[1:]), facebook_token)
  File "/anaconda/lib/python2.7/site-packages/tindetheus/tindetheus.py", line 501, in main
    my_sess.browse()
  File "/anaconda/lib/python2.7/site-packages/tindetheus/tindetheus.py", line 459, in browse
    self.look_at_users(users)
  File "/anaconda/lib/python2.7/site-packages/tindetheus/tindetheus.py", line 326, in look_at_users
    show_images(image_list)
  File "/anaconda/lib/python2.7/site-packages/tindetheus/tindetheus.py", line 153, in show_images
    temp_image = imageio.imread(i)
  File "/anaconda/lib/python2.7/site-packages/imageio/core/functions.py", line 200, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/anaconda/lib/python2.7/site-packages/imageio/core/functions.py", line 126, in get_reader
    'in mode %r' % mode)
ValueError: Could not find a format to read the specified file in mode 'i'

**Comment by cjekel** [comment] 2018-03-14 23:45
Seems like a problem with your imageio install https://github.com/imageio/imageio/issues/126

How did you install imageio? If it installed with pip, you may want to uninstall
```
pip uninstall imageio
```
then install with conda
```
conda install -c conda-forge imageio
```

**Comment by cjekel** [comment] 2018-11-01 23:09
Hey I'm interested in helping you troubleshoot this, but I've been unable to reproduce the imageio issue. Last I checked *tindetheus* worked in a Fresh anaconda environment on OS X Yosemite. 

I'm going to close the issue for now, but feel free to reopen it and comment!

**Closed by cjekel** 2018-11-01 23:09 UTC
